In [1]:
rawdat = readlines(open("nmtable.csv"))

1-element Array{ByteString,1}:
 "TABLE 1\rdose,id,Time,DV,OBSNAME,REPLICATE\r600,1102,0.5,0.239793,CObs,0\r600,1102,1,0.550765,CObs,0\rTABLE 1\rdose,id,Time,DV,OBSNAME,REPLICATE\r600,1102,0.5,0.239793,CObs,1\r600,1102,1,0.550765,CObs,1\rTABLE 1\rdose,id,Time,DV,OBSNAME,REPLICATE\r600,1102,0.5,0.239793,CObs,2\r600,1102,1,0.550765,CObs,2"

In [3]:
eachline(open("nmtable.csv"))

EachLine(IOStream(<file nmtable.csv>),(anonymous function))

INFO: Cloning cache of BufferedStreams from git://github.com/BioJulia/BufferedStreams.jl.git
INFO: Cloning cache of CSV from git://github.com/JuliaDB/CSV.jl.git
INFO: Cloning cache of DataStreams from git://github.com/JuliaDB/DataStreams.jl.git
INFO: Cloning cache of Libz from git://github.com/BioJulia/Libz.jl.git
INFO: Cloning cache of NullableArrays from git://github.com/JuliaStats/NullableArrays.jl.git
INFO: Installing BufferedStreams v0.0.2
INFO: Installing CSV v0.0.4
INFO: Installing DataStreams v0.0.3
INFO: Installing Libz v0.0.2
INFO: Installing NullableArrays v0.0.2
INFO: Package database updated


In [3]:
using DataFrames
using CSV

In [5]:
rawdat = readlines(open("nmtable"))

15-element Array{Union(ASCIIString,UTF8String),1}:
 "TABLE NO.  1\n"                                                                                                            
 " ID         ,REP        ,TIME       ,DV         ,IPRED      ,PRED       ,AMT        ,DOSE       ,ISM        ,MDV\n"        
 "  1.0000E+00, 1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 2.5000E-01, 2.4470E+01, 2.2400E+01, 2.9931E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 5.0000E-01, 4.9541E+01, 3.8780E+01, 4.9995E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "TABLE NO.  1\n"                                                                                                            
 " ID         ,REP        ,TIME       ,DV         ,IPRED      ,PRED       ,AMT        ,DOSE       ,ISM        ,MDV\n"        
 "  1.0000E+00, 2.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0

In [6]:
rawdat[1][1] .=='T'

true

In [4]:
contains(rawdat[1], "TABLE")

true

In [8]:
matchall("TABLE", rawdat)

LoadError: `matchall` has no method matching matchall(::ASCIIString, ::Array{Union(ASCIIString,UTF8String),1})
while loading In[8], in expression starting on line 1

In [9]:
rmlines = zeros(0)
for (i, x) in enumerate(rawdat)
    if(ismatch(r"(TABLE|ID)", x)) 
        push!(rmlines, i)
    end
end

In [10]:
rmlines

6-element Array{Float64,1}:
  1.0
  2.0
  6.0
  7.0
 11.0
 12.0

In [11]:
rawdat[rmlines]

6-element Array{Union(ASCIIString,UTF8String),1}:
 "TABLE NO.  1\n"                                                                                                    
 " ID         ,REP        ,TIME       ,DV         ,IPRED      ,PRED       ,AMT        ,DOSE       ,ISM        ,MDV\n"
 "TABLE NO.  1\n"                                                                                                    
 " ID         ,REP        ,TIME       ,DV         ,IPRED      ,PRED       ,AMT        ,DOSE       ,ISM        ,MDV\n"
 "  TABLE NO.  1\n"                                                                                                  
 " ID         ,REP        ,TIME       ,DV         ,IPRED      ,PRED       ,AMT        ,DOSE       ,ISM        ,MDV\n"

In [12]:
keeplines = similar(rawdat[3:4], 0)
for (i, x) in enumerate(rawdat)
    if(!ismatch(r"(TABLE|ID)", x)) 
        push!(keeplines, x)
    end
end

In [13]:
keeplines

9-element Array{Union(ASCIIString,UTF8String),1}:
 "  1.0000E+00, 1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 2.5000E-01, 2.4470E+01, 2.2400E+01, 2.9931E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 5.0000E-01, 4.9541E+01, 3.8780E+01, 4.9995E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 2.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"
 "  1.0000E+00, 2.0000E+00, 2.5000E-01, 2.4470E+01, 2.2400E+01, 2.9931E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 2.0000E+00, 5.0000E-01, 4.9541E+01, 3.8780E+01, 4.9995E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 3.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"
 "  1.0000E+00, 3.0000E+00, 2.5000E-01, 2.4470E+01, 2.2400E+01, 2.99

In [14]:
using DataFrames

In [15]:
keeplines[1]

"  1.0000E+00, 1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"

In [16]:
lstrip(keeplines[1])

"1.0000E+00, 1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"

In [17]:
replace(rawdat[2], " ", "")

"ID,REP,TIME,DV,IPRED,PRED,AMT,DOSE,ISM,MDV\n"

In [18]:
wdat = replace(rawdat[2], " ", "")

"ID,REP,TIME,DV,IPRED,PRED,AMT,DOSE,ISM,MDV\n"

In [20]:
wdat = [replace(rawdat[2], " ", ""), keeplines]

10-element Array{UTF8String,1}:
 "ID,REP,TIME,DV,IPRED,PRED,AMT,DOSE,ISM,MDV\n"                                                                              
 "  1.0000E+00, 1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 2.5000E-01, 2.4470E+01, 2.2400E+01, 2.9931E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 5.0000E-01, 4.9541E+01, 3.8780E+01, 4.9995E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 2.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"
 "  1.0000E+00, 2.0000E+00, 2.5000E-01, 2.4470E+01, 2.2400E+01, 2.9931E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 2.0000E+00, 5.0000E-01, 4.9541E+01, 3.8780E+01, 4.9995E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 3.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02

In [21]:
write(wdat, "cleanednmtable.csv")

LoadError: `write` has no method matching write(::Array{UTF8String,1}, ::ASCIIString)
while loading In[21], in expression starting on line 1

In [22]:
c = open("cleanednmtable.csv", "w+")

IOStream(<file cleanednmtable.csv>)

In [23]:
write(c, wdat)

1131

In [24]:
close(c)

In [25]:
readtable("cleanednmtable.csv")

9x10 DataFrame
| Row | ID  | REP | TIME | DV     | IPRED | PRED   | AMT   | DOSE  | ISM | MDV |
|-----|-----|-----|------|--------|-------|--------|-------|-------|-----|-----|
| 1   | 1.0 | 1.0 | 0.0  | 0.0    | 0.0   | 0.0    | 150.0 | 150.0 | 1.0 | 1.0 |
| 2   | 1.0 | 1.0 | 0.25 | 24.47  | 22.4  | 29.931 | 0.0   | 150.0 | 1.0 | 0.0 |
| 3   | 1.0 | 1.0 | 0.5  | 49.541 | 38.78 | 49.995 | 0.0   | 150.0 | 1.0 | 0.0 |
| 4   | 1.0 | 2.0 | 0.0  | 0.0    | 0.0   | 0.0    | 150.0 | 150.0 | 1.0 | 1.0 |
| 5   | 1.0 | 2.0 | 0.25 | 24.47  | 22.4  | 29.931 | 0.0   | 150.0 | 1.0 | 0.0 |
| 6   | 1.0 | 2.0 | 0.5  | 49.541 | 38.78 | 49.995 | 0.0   | 150.0 | 1.0 | 0.0 |
| 7   | 1.0 | 3.0 | 0.0  | 0.0    | 0.0   | 0.0    | 150.0 | 150.0 | 1.0 | 1.0 |
| 8   | 1.0 | 3.0 | 0.25 | 24.47  | 22.4  | 29.931 | 0.0   | 150.0 | 1.0 | 0.0 |
| 9   | 1.0 | 3.0 | 0.5  | 49.541 | 38.78 | 49.995 | 0.0   | 150.0 | 1.0 | 0.0 |

In [5]:
function cleannm(filename, headerrow=2)
    rawdat = readlines(open(filename))
    keeplines = similar(rawdat[3:4], 0)
    for x in rawdat
        if(!ismatch(r"(TABLE|ID)", x)) 
            push!(keeplines, lstrip(x))
        end
    end
    wdat = [replace(rawdat[headerrow], " ", ""), keeplines]
    c = open(filename*"cleaned", "w+")
    write(c, wdat)
    close(c)
    println("successfully cleaned")
end

cleannm (generic function with 2 methods)

In [6]:
cleannm("nmtable")

successfully cleaned


 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in vect at abstractarray.jl:38
 in cleannm at In[5]:9
 in cleannm at In[5]:2
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at /Users/devin/.julia/v0.4/IJulia/src/execute_request.jl:177
 in eventloop at /Users/devin/.julia/v0.4/IJulia/src/IJulia.jl:141
 in anonymous at task.jl:447
while loading In[6], in expression starting on line 1


In [9]:
@time cleannm("/Users/devin/run001QPCshiny")

successfully cleaned
  0.533284 seconds (1.26 M allocations: 87.769 MB, 15.76% gc time)


In [17]:
@time readlines(open("/Users/devin/run001QPCshiny"))

180600-element Array{ByteString,1}:
 "TABLE NO.  1\n"                                                                                                            
 " ID         ,REP        ,TIME       ,DV         ,IPRED      ,PRED       ,AMT        ,DOSE       ,ISM        ,MDV\n"        
 "  1.0000E+00, 1.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 0.0000E+00, 1.5000E+02, 1.5000E+02, 1.0000E+00, 1.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 2.5000E-01, 2.4470E+01, 2.2400E+01, 2.9931E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 5.0000E-01, 4.9541E+01, 3.8780E+01, 4.9995E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 1.0000E+00, 5.6510E+01, 5.8644E+01, 6.9981E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 1.5000E+00, 6.3165E+01, 6.7310E+01, 7.3799E+01, 0.0000E+00, 1.5000E+02, 1.0000E+00, 0.0000E+00\n"
 "  1.0000E+00, 1.0000E+00, 2.0000E+00, 6.6649E+01, 6.9466E+01, 6.9487E+01, 0.0000

0.070973 seconds (361.41 k allocations: 38.818 MB, 26.47% gc time)


In [10]:
@time readtable("/Users/devin/run001QPCshinycleaned")

180000x10 DataFrames.DataFrame
| Row    | ID   | REP   | TIME | DV     | IPRED  | PRED   | AMT   | DOSE  |
|--------|------|-------|------|--------|--------|--------|-------|-------|
| 1      | 1.0  | 1.0   | 0.0  | 0.0    | 0.0    | 0.0    | 150.0 | 150.0 |
| 2      | 1.0  | 1.0   | 0.25 | 24.47  | 22.4   | 29.931 | 0.0   | 150.0 |
| 3      | 1.0  | 1.0   | 0.5  | 49.541 | 38.78  | 49.995 | 0.0   | 150.0 |
| 4      | 1.0  | 1.0   | 1.0  | 56.51  | 58.644 | 69.981 | 0.0   | 150.0 |
| 5      | 1.0  | 1.0   | 1.5  | 63.165 | 67.31  | 73.799 | 0.0   | 150.0 |
| 6      | 1.0  | 1.0   | 2.0  | 66.649 | 69.466 | 69.487 | 0.0   | 150.0 |
| 7      | 1.0  | 1.0   | 2.5  | 68.544 | 67.95  | 61.606 | 0.0   | 150.0 |
| 8      | 1.0  | 1.0   | 3.0  | 73.278 | 64.47  | 52.659 | 0.0   | 150.0 |
| 9      | 1.0  | 1.0   | 4.0  | 57.976 | 55.263 | 36.065 | 0.0   | 150.0 |
| 10     | 1.0  | 1.0   | 6.0  | 31.794 | 37.554 | 14.931 | 0.0   | 150.0 |
| 11     | 1.0  | 1.0   | 8.0  | 25.82  | 24.776 | 5.7837 | 0.0   | 150.0 |
⋮
| 179989 | 50.0 | 300.0 | 0.0  | 0.0    | 0.0    | 0.0    | 150.0 | 150.0 |
| 179990 | 50.0 | 300.0 | 0.25 | 20.907 | 21.858 | 31.496 | 0.0   | 150.0 |
| 179991 | 50.0 | 300.0 | 0.5  | 40.072 | 39.476 | 55.512 | 0.0   | 150.0 |
| 179992 | 50.0 | 300.0 | 1.0  | 76.009 | 64.74  | 87.22  | 0.0   | 150.0 |
| 179993 | 50.0 | 300.0 | 1.5  | 81.223 | 80.214 | 104.33 | 0.0   | 150.0 |
| 179994 | 50.0 | 300.0 | 2.0  | 99.581 | 88.976 | 112.54 | 0.0   | 150.0 |
| 179995 | 50.0 | 300.0 | 2.5  | 80.017 | 93.17  | 115.35 | 0.0   | 150.0 |
| 179996 | 50.0 | 300.0 | 3.0  | 87.789 | 94.288 | 114.92 | 0.0   | 150.0 |
| 179997 | 50.0 | 300.0 | 4.0  | 87.315 | 91.108 | 109.22 | 0.0   | 150.0 |
| 179998 | 50.0 | 300.0 | 6.0  | 67.181 | 76.652 | 92.431 | 0.0   | 150.0 |
| 179999 | 50.0 | 300.0 | 8.0  | 58.595 | 61.452 | 76.542 | 0.0   | 150.0 |
| 180000 | 50.0 | 300.0 | 12.0 | 40.801 | 38.263 | 52.057 | 0.0   | 150.0 |

| Row    | ISM | MDV |
|--------|-----|-----|
| 1      | 1.0 | 1.0 |
| 2      | 1.0 | 0.0 |
| 3      | 1.0 | 0.0 |
| 4      | 1.0 | 0.0 |
| 5      | 1.0 | 0.0 |
| 6      | 1.0 | 0.0 |
| 7      | 1.0 | 0.0 |
| 8      | 1.0 | 0.0 |
| 9      | 1.0 | 0.0 |
| 10     | 1.0 | 0.0 |
| 11     | 1.0 | 0.0 |
⋮
| 179989 | 0.0 | 1.0 |
| 179990 | 0.0 | 0.0 |
| 179991 | 0.0 | 0.0 |
| 179992 | 0.0 | 0.0 |
| 179993 | 0.0 | 0.0 |
| 179994 | 0.0 | 0.0 |
| 179995 | 0.0 | 0.0 |
| 179996 | 0.0 | 0.0 |
| 179997 | 0.0 | 0.0 |
| 179998 | 0.0 | 0.0 |
| 179999 | 0.0 | 0.0 |
| 180000 | 0.0 | 0.0 |

1.173764 seconds (9.00 M allocations: 233.340 MB, 37.51% gc time)


In [8]:
@time readcsv("/Users/devin/run001QPCshinycleaned")

180001x10 Array{Any,2}:
   "ID"     "REP"    "TIME"    "DV"  …     "AMT"     "DOSE"   "ISM"   "MDV"
  1.0      1.0      0.0       0.0       150.0     150.0      1.0     1.0   
  1.0      1.0      0.25     24.47        0.0     150.0      1.0     0.0   
  1.0      1.0      0.5      49.541       0.0     150.0      1.0     0.0   
  1.0      1.0      1.0      56.51        0.0     150.0      1.0     0.0   
  1.0      1.0      1.5      63.165  …    0.0     150.0      1.0     0.0   
  1.0      1.0      2.0      66.649       0.0     150.0      1.0     0.0   
  1.0      1.0      2.5      68.544       0.0     150.0      1.0     0.0   
  1.0      1.0      3.0      73.278       0.0     150.0      1.0     0.0   
  1.0      1.0      4.0      57.976       0.0     150.0      1.0     0.0   
  1.0      1.0      6.0      31.794  …    0.0     150.0      1.0     0.0   
  1.0      1.0      8.0      25.82        0.0     150.0      1.0     0.0   
  1.0      1.0     12.0      10.788       0.0     150.0      1.0

1.103296 seconds (7.20 M allocations: 226.526 MB, 47.08% gc time)


In [11]:
@time cleaned_data = CSV.read("/Users/devin/run001QPCshinycleaned")

Data.Table:
180000x10 Data.Schema:
      ID,     REP,    TIME,      DV,   IPRED,    PRED,     AMT,    DOSE,     ISM,     MDV
 Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64
NullableArrays.NullableArray{T,1}[NullableArrays.NullableArray{Float64,1}[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0  …  50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0],NullableArrays.NullableArray{Float64,1}[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0  …  300.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0],NullableArrays.NullableArray{Float64,1}[0.0,0.25,0.5,1.0,1.5,2.0,2.5,3.0,4.0,6.0  …  0.5,1.0,1.5,2.0,2.5,3.0,4.0,6.0,8.0,12.0],NullableArrays.NullableArray{Float64,1}[0.0,24.47,49.541,56.51,63.165,66.649,68.544,73.278,57.976,31.794  …  40.072,76.009,81.223,99.581,80.017,87.789,87.315,67.181,58.595,40.801],NullableArrays.NullableArray{Float64,1}[0.0,22.4,38.78,58.644,67.31,69.466,67.95,64.47,55.263,37.554  …  39.476,64.74,80.214,88.976,93.17,94.288,91.108,76.652,61.45

0.351470 seconds (1.81 M allocations: 43.476 MB, 9.55% gc time)


In [12]:
DataFrame(convert(Vector{Any},cleaned_data.data),Symbol[symbol(x) for x in cleaned_data.schema.header])

180000x10 DataFrames.DataFrame
| Row    | ID             | REP             | TIME           |
|--------|----------------|-----------------|----------------|
| 1      | Nullable(1.0)  | Nullable(1.0)   | Nullable(0.0)  |
| 2      | Nullable(1.0)  | Nullable(1.0)   | Nullable(0.25) |
| 3      | Nullable(1.0)  | Nullable(1.0)   | Nullable(0.5)  |
| 4      | Nullable(1.0)  | Nullable(1.0)   | Nullable(1.0)  |
| 5      | Nullable(1.0)  | Nullable(1.0)   | Nullable(1.5)  |
| 6      | Nullable(1.0)  | Nullable(1.0)   | Nullable(2.0)  |
| 7      | Nullable(1.0)  | Nullable(1.0)   | Nullable(2.5)  |
| 8      | Nullable(1.0)  | Nullable(1.0)   | Nullable(3.0)  |
| 9      | Nullable(1.0)  | Nullable(1.0)   | Nullable(4.0)  |
| 10     | Nullable(1.0)  | Nullable(1.0)   | Nullable(6.0)  |
| 11     | Nullable(1.0)  | Nullable(1.0)   | Nullable(8.0)  |
⋮
| 179989 | Nullable(50.0) | Nullable(300.0) | Nullable(0.0)  |
| 179990 | Nullable(50.0) | Nullable(300.0) | Nullable(0.25) |
| 179991 | Nullable(50.0) | Nullable(300.0) | Nullable(0.5)  |
| 179992 | Nullable(50.0) | Nullable(300.0) | Nullable(1.0)  |
| 179993 | Nullable(50.0) | Nullable(300.0) | Nullable(1.5)  |
| 179994 | Nullable(50.0) | Nullable(300.0) | Nullable(2.0)  |
| 179995 | Nullable(50.0) | Nullable(300.0) | Nullable(2.5)  |
| 179996 | Nullable(50.0) | Nullable(300.0) | Nullable(3.0)  |
| 179997 | Nullable(50.0) | Nullable(300.0) | Nullable(4.0)  |
| 179998 | Nullable(50.0) | Nullable(300.0) | Nullable(6.0)  |
| 179999 | Nullable(50.0) | Nullable(300.0) | Nullable(8.0)  |
| 180000 | Nullable(50.0) | Nullable(300.0) | Nullable(12.0) |

| Row    | DV               | IPRED            | PRED             |
|--------|------------------|------------------|------------------|
| 1      | Nullable(0.0)    | Nullable(0.0)    | Nullable(0.0)    |
| 2      | Nullable(24.47)  | Nullable(22.4)   | Nullable(29.931) |
| 3      | Nullable(49.541) | Nullable(38.78)  | Nullable(49.995) |
| 4      | Nullable(56.51)  | Nullable(58.644) | Nullable(69.981) |
| 5      | Nullable(63.165) | Nullable(67.31)  | Nullable(73.799) |
| 6      | Nullable(66.649) | Nullable(69.466) | Nullable(69.487) |
| 7      | Nullable(68.544) | Nullable(67.95)  | Nullable(61.606) |
| 8      | Nullable(73.278) | Nullable(64.47)  | Nullable(52.659) |
| 9      | Nullable(57.976) | Nullable(55.263) | Nullable(36.065) |
| 10     | Nullable(31.794) | Nullable(37.554) | Nullable(14.931) |
| 11     | Nullable(25.82)  | Nullable(24.776) | Nullable(5.7837) |
⋮
| 179989 | Nullable(0.0)    | Nullable(0.0)    | Nullable(0.0)    |
| 179990 | Nullable(20.907) | Nullable(21.858) | Nullable(31.496) |
| 179991 | Nullable(40.072) | Nullable(39.476) | Nullable(55.512) |
| 179992 | Nullable(76.009) | Nullable(64.74)  | Nullable(87.22)  |
| 179993 | Nullable(81.223) | Nullable(80.214) | Nullable(104.33) |
| 179994 | Nullable(99.581) | Nullable(88.976) | Nullable(112.54) |
| 179995 | Nullable(80.017) | Nullable(93.17)  | Nullable(115.35) |
| 179996 | Nullable(87.789) | Nullable(94.288) | Nullable(114.92) |
| 179997 | Nullable(87.315) | Nullable(91.108) | Nullable(109.22) |
| 179998 | Nullable(67.181) | Nullable(76.652) | Nullable(92.431) |
| 179999 | Nullable(58.595) | Nullable(61.452) | Nullable(76.542) |
| 180000 | Nullable(40.801) | Nullable(38.263) | Nullable(52.057) |

| Row    | AMT             | DOSE            | ISM           | MDV           |
|--------|-----------------|-----------------|---------------|---------------|
| 1      | Nullable(150.0) | Nullable(150.0) | Nullable(1.0) | Nullable(1.0) |
| 2      | Nullable(0.0)   | Nullable(150.0) | Nullable(1.0) | Nullable(0.0) |
| 3      | Nullable(0.0)   | Nullable(150.0) | Nullable(1.0) | Nullable(0.0) |
| 4      | Nullable(0.0)   | Nullable(150.0) | Nullable(1.0) | Nullable(0.0) |
| 5      | Nullable(0.0)   | Nullable(150.0) | Nullable(1.0) | Nullable(0.0) |
| 6      | Nullable(0.0)   | Nullable(150.0) | Nullable(1.0) | Nullable(0.0) |
| 7      | Nullable(0.0)   | Nullable(150.0) | Nullable(

In [14]:
function f()
    readtable("/Users/devin/run001QPCshinycleaned")
end
f()
benchmark(f, "read benchmark", "readtable", 10)

LoadError: LoadError: UndefVarError: benchmark not defined
while loading In[14], in expression starting on line 5

Note that the shiny QPC data is ~ 25 MB and takes about 3.3 seconds for normal read.csv and only ~0.13 seconds for fastread packages in R