In [ ]:
x::Array{Float64, 1}
left = 
right = 


n::Int8 = size(x)
bin::Int8 = size(left);
out = zeros(n)
  
  
  
  return out;

In [2]:
using DataFrames
using Distributions

In [6]:
rand(Uniform(1, 10),10)

10-element Array{Float64,1}:
 7.98667
 5.00674
 6.16215
 3.97044
 3.26152
 7.22805
 5.51282
 3.08246
 5.4968 
 8.67728

In [26]:
df = DataFrame()
df[:binvalue] = rand(Uniform(1, 10),100)

100-element Array{Float64,1}:
 2.89632
 7.27417
 9.16728
 9.95101
 2.16026
 1.89077
 8.47464
 9.78793
 9.53963
 3.68529
 1.91815
 3.33137
 5.32646
 ⋮      
 4.87274
 3.72044
 6.51892
 6.05029
 9.74496
 6.75783
 2.63809
 6.35063
 7.05611
 1.68183
 6.86664
 3.19513

In [36]:
x = df[:binvalue]
left = [1.0, 5.0, 8.0]
right = [5.0, 8.0, 10]
out = fill(0, length(x))

100-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [37]:
for i in 1:length(x) 
    for j in 1:length(left) 
        if ( (x[i] >= left[j]) && (x[i] < right[j]))
        out[i] = j;
            break
         else 
           continue
         end
    end
end

In [38]:
out

100-element Array{Int64,1}:
 1
 2
 3
 3
 1
 1
 3
 3
 3
 1
 1
 1
 2
 ⋮
 1
 1
 2
 2
 3
 2
 1
 2
 2
 1
 2
 1

In [42]:
function set_bins(x::DataArray{Float64, 1}, left::Array{Float64, 1}, right::Array{Float64, 1})
    out = fill(0, length(x))
    for i in 1:length(x) 
        for j in 1:length(left) 
            if ( (x[i] >= left[j]) && (x[i] < right[j]))
            out[i] = j;
                break
             else 
               continue
             end
        end
    end
    return out
end

set_bins (generic function with 2 methods)

In [45]:
@time set_bins(x, left, right)

elapsed time: 2.558e-5 seconds (12112 bytes allocated)


100-element Array{Int64,1}:
 1
 2
 3
 3
 1
 1
 3
 3
 3
 1
 1
 1
 2
 ⋮
 1
 1
 2
 2
 3
 2
 1
 2
 2
 1
 2
 1